// Generated by CoffeeScript 1.7.1
var Deferred, WebElement, fs, path, selenium;

path = require('path');

fs = require('fs');

selenium = require('selenium-webdriver');

Deferred = selenium.promise.Deferred;

WebElement = selenium.WebElement;

module.exports = function(driver) {
  var all, checkSizzleExists, getElement, injectSizzle, one;
  checkSizzleExists = function() {
    return driver.executeScript(function() {
      return window.Sizzle != null;
    });
  };
  injectSizzle = function() {
    var sizzleCode;
    sizzleCode = fs.readFileSync(path.join(__dirname, '../lib', 'sizzle.min.js'));
    return driver.executeScript("var module = {exports: {}};\n" + sizzleCode + "\nwindow.Sizzle = module.exports;");
  };
  getElement = function(selector) {
    var elementPromise;
    elementPromise = driver.findElement(selenium.By.js(function(selector) {
      return (window.Sizzle(selector) || [])[0];
    }, selector));
    elementPromise.then(null, function(err) {
      throw new Error("Selector " + selector + " matches nothing");
    });
    return elementPromise;
  };
  one = function(selector) {
    var d;
    d = new Deferred;
    checkSizzleExists().then(function(sizzleExists) {
      if (!sizzleExists) {
        return injectSizzle();
      }
    }).then(function() {
      var elPromise;
      elPromise = getElement(selector);
      return d.fulfill(elPromise);
    });
    return new WebElement(driver, d.promise);
  };
  all = function(selector) {
    var sizzleCode;
    sizzleCode = fs.readFileSync(path.join(__dirname, '../lib', 'sizzle.min.js'));
    return driver.findElements(selenium.By.js("var module = {exports: {}};\n" + sizzleCode + "\nvar Sizzle = module.exports;\nreturn (Sizzle(" + (JSON.stringify(selector)) + ") || []);"));
  };
  one.all = all;
  return one;
};
