// Generated by CoffeeScript 1.7.1
var fs, path, selenium;

selenium = require('selenium-webdriver');

path = require('path');

fs = require('fs');

module.exports = function(driver) {
  var all, one, sizzleCode;
  sizzleCode = fs.readFileSync(path.join(__dirname, '../lib', 'sizzle.min.js'));
  one = function(selector) {
    return driver.findElement(selenium.By.js("var module = {exports: {}};\n" + sizzleCode + "\nvar Sizzle = module.exports;\nreturn (Sizzle(" + (JSON.stringify(selector)) + ") || [])[0];"));
  };
  all = function(selector) {
    return driver.findElements(selenium.By.js("var module = {exports: {}};\n" + sizzleCode + "\nvar Sizzle = module.exports;\nreturn (Sizzle(" + (JSON.stringify(selector)) + ") || []);"));
  };
  one.all = all;
  return one;
};
